name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to deploy to production?'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'CodeFatherG' && inputs.confirm && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.BOT_DEPLOY_KEY }}

    - name: Configure git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'github-actions@github.com'
        git remote set-url origin git@github.com:${{ github.repository }}.git

    - name: Merge main to release
      run: |
        git checkout release
        git merge origin/main
        git push origin release

    - name: Deployment status
      if: success()
      run: echo "Deployment successful!"

    - name: Deployment failure
      if: failure()
      run: echo "Deployment failed. Please check the logs for details."